# Generated by Django 5.0.1 on 2024-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='user_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
